### ISSUE TITLE
data of india is showing wrong

### ISSUE THREAD

**Issue by saikatkoley** [BaseMax/CoronaVirusOutbreakAPI#2]
data of india is showing wrong

**Comment by BaseMax** [comment]
Hello Dear @saikatkoley,

Thanks you for report this.
I did patch it, They change website structure, and it's why need to modify regular expression.

Anyway, this works great at now.

If you are looking for a stable API, you can check this repository:
https://github.com/BaseMax/CoronaVirusDatabase

Regards,
Max Base

**Comment by BaseMax** [comment]
Thanks to again,
